version: 0.0
os: linux         # 현재 EC2 Linux2를 사용하고 있습니다.
files:
  - source:  /   # 프로젝트 전체를 의미
    destination: /home/ec2-user/app/naverapi/zip/   # EC2 내부에 해당 위치에 파일을 옮기겠다는 뜻 (본인이 원하는 곳을 지정하면 됩니다.)
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: deploy.sh  # ApplicationStart 에서 deploy.sh를 실행합니다.
      timeout: 60
      runas: ec2-user