spring:
  profiles:
    include: stratospheric
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  thymeleaf:
    prefix : classpath:/static/
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        SQL: debug
        format_sql: true
cloud:
  aws:
    stack:
      auto: false
logging:
  level:
    org.hibernate.type.descriptor.sql: trace

