server:
  port: 8082
spring:
  profiles:
    include: oauth, real-db, stratospheric
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  session:
    store-type: jdbc